project:
  title: "Futureverse P2P: Peer-to-Peer Parallelization in R"
  
format:
  revealjs:
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: images/future-logo.png
    footer: <https://future.p2p.futureverse.org>
    slide-number: true
    margin: 0.05
    pointer:
      pointerSize: 32

revealjs-plugins:
  - pointer
  - bsicons
